version: '3'
services:
  app:
    container_name: color
    image: cleonia/color
    ports:
      - "8080:8080"

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8080:8080"